import type { Metadata } from "next";
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          <header></header>
          <main>
            <div className="flex min-h-screen flex-col items-center gap-5 bg-gradient-to-tr from-sky-100 via-emerald-50 to-yellow-100">
              <Navbar />
              {children}
              <Footer />
            </div>
          </main>
        </body>
      </html>
    </ClerkProvider>
  );
}
